#!/bin/sh

# the path of the file containing "secret" info varies on the instance name
# (/etc/minetest/secrets/$instance.conf),
# so changing that in instance_name.txt changes the path of a build dependency.
# to capture that properly, we need to get ninja to rebuild itself.

instance="$(cat "$2")" || exit $?;
base_ninja="$1";

# base rules
cat "$base_ninja" || exit $?;



basepath="/etc/minetest/secrets";

# the below stdout rule requires the scripts to be in a subdir,
# as ninja normalises the path to not have ./,
# but shells refuse to run unqualified programs in CWD for security reasons.
cat << EOF
rule stdout_to_file
  command = \$in > \$out

build build.ninja: stdout_to_file regen/regen_ninja base.ninja instance_name.txt

rule cat
  command = cat \$in > \$out

build world_data/minetest.conf: cat minetest.conf.in ${basepath}/${instance}.conf
EOF

